version: "3.7"
services:
  db:
    image: mysql:8.0.21
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
    volumes: 
      - "./init/:/docker-entrypoint-initdb.d/"
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql-tuning-practice
    